name: ci-cd-github

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ci-cd-demo
  REGISTRY: ghcr.io/jgak
  GIT_SHA: ${{ github.sha }}

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        working-directory: ./app
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${GIT_SHA} .

      - name: Smoke test
        run: |
          docker run -d -p 8080:80 --name ci-cd-test $REGISTRY/$IMAGE_NAME:${GIT_SHA}
          sleep 3
          curl -f http://localhost:8080 | grep -E 'Bienvenue|Version|Deployee|Deploy'
          docker rm -f ci-cd-test

      - name: Push image to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${GIT_SHA}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [ build_test_push ]
    runs-on: self-hosted
    steps:
      - name: Préparer le contexte Minikube
        run: |
          minikube update-context
          kubectl config use-context minikube
          kubectl get nodes

      - name: Déploiement Helm (upgrade/install)
        env:
          IMAGE_REPO: ghcr.io/jgak/ci-cd-demo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd /opt/ci-cd-demo/ci-cd-demo-chart
          helm upgrade --install ci-cd-demo . \
            --set image.repository=${IMAGE_REPO} \
            --set image.tag=${IMAGE_TAG} \
            --set replicaCount=3 \
            --set service.type=NodePort \
            --set service.port=80 \
            --set service.nodePort=30080 \
            --set ingress.enabled=false \
            --set httpRoute.enabled=false
          helm history ci-cd-demo

      - name: Vérification du rollout
        run: |
          kubectl rollout status deployment/ci-cd-demo --timeout=180s
          kubectl get deploy,po,svc -o wide
